version: "3.9"

services:
  web:
    image: api
    build: .
    ports:
      - 5001:5001
    networks:
      - default
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
    - POSTGRES_PASSWORD=Test1 
    - POSTGRES_USER=admin
    ports:
    - '5432:5432'
    networks:
      - default

networks:
  interlnal:
    name: internal
    external: true
    driver: "bridge"